[package]
name = "ferrostar"
version = "0.0.18"
readme = "README.md"
description = "The core of modern turn-by-turn navigation."
keywords = ["navigation", "routing", "valhalla", "osrm"]
categories = ["science::geo"]
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.28.0"
polyline = "0.10.0"
serde = { version = "1.0.162", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
uniffi.workspace = true

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }

[dev-dependencies]
assert-json-diff = "2.0.2"
proptest = "1.3.1"
insta = { version = "1.33.0", features = ["yaml"] }

[lib]
crate-type = ["cdylib", "staticlib", "lib"]
