[workspace]

members = [
    "uniffi-bindgen",
    "ferrostar",
]
resolver = "2"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[workspace.dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "41e3f953ed6e3d8e10cde262dd269b683ac49f0e" }