[workspace]

members = [
    "uniffi-bindgen",
    "ferrostar",
]
resolver = "2"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.release]
lto = "thin"
opt-level = "s"

[workspace.dependencies]
uniffi = "0.26.1"