[workspace]

members = [
    "uniffi-bindgen",
    "ferrostar-core",
]
resolver = "2"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[workspace.dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "46c06003261c9ce769afff735f8d29d4282f445c" }