[workspace]

members = [
    "uniffi-bindgen",
    "ferrostar",
]
resolver = "2"

[profile.dev.package]
insta.opt-level = 3
similar.opt-level = 3

[profile.release]
lto = "thin"
opt-level = "s"

[workspace.dependencies]
uniffi = { git = "https://github.com/mozilla/uniffi-rs/", rev = "fbc6631953a889c7af6e5f1af94de9242589b75b" }