name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Create an Android Virtual Device
      run: $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n emulator -k "system-images;android-33;google_apis;x86_64"

    - name: Launch the emulator
      run: $ANDROID_HOME/emulator/emulator -avd emulator

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Touch local.properties (required for cargo-ndk)
      run: touch local.properties
      working-directory: android
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: android

    - name: Run Android Tests
      run: ./gradlew connectedAndroidTest
      working-directory: android
