name: Android CI

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: android

    - name: Install cargo-ndk
      run: cargo install cargo-ndk

    - name: Touch local.properties (required for cargo-ndk)
      run: touch local.properties
      working-directory: android

    - name: Check formatting
      run: ./gradlew ktfmtCheck
      working-directory: android
      
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: android

    - name: Run Connected Checks
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        arch: arm64-v8a
        target: aosp_atd
        script: ./gradlew connectedCheck
        working-directory: android
