name: Rust (Common)

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cargo Build
      run: cargo build --verbose
      working-directory: common
    - name: Run tests
      run: cargo test --verbose
      working-directory: common
