name: WASM (JS)
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Install wasm-pack
        run: cargo install wasm-pack
        
      - name: WASM Build
        run: wasm-pack build --target web ferrostar --no-default-features --features wasm_js
        working-directory: common

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          
      - run: npm ci
        working-directory: web

      - run: npm run build
        working-directory: web

      - name: WASM unit tests
        run: wasm-pack test --firefox --headless ferrostar --no-default-features --features wasm_js
